pos_system = {
    'names': ['Avery', 'Melody', 'Rufus', 'Sabrina', 'Michael', 'Rubin', 'James', 'Vic', 'Ace', 'Marco', 'Veronica', 'Chris', 'Anita', 'Loie', 'Maya', 'Nadia', 'Lola'],
    "menus": ['entrees', 'sides', 'beverages', 'desserts'],
    'menu_items': {
        'entrees': [
            {'item': 'Coconut Shrimp', 'price': 17},
            {'item': 'Braised Pork Chops', 'price': 24}, 
            {'item': 'Cedar Plank Salmon', 'price': 32},
            {'item': 'Chilean Seabass', 'price': 32}, 
            {'item': 'Chicken Picatta', 'price': 28}, 
            {'item': 'Cajun Shrimp Pasta', 'price': 28}, 
            {'item': 'Pepper Steak', 'price': 18},
            {'item': 'Clubhouse Sandwich', 'price': 14},
            {'item': 'Wagyu Burger', 'price': 16},
            {'item': 'Birria Tacos', 'price': 14},
            {'item': 'Lamb Kebabs', 'price': 18},
            {'item': 'Buffalo Calzone', 'price': 16}, 
            {'item': 'Jambalaya', 'price': 16}, 
            {'item': 'Chicken Pot Pie', 'price': 20}, 
            {'item': 'Seafood Lasagna', 'price': 23},
            {'item': 'Grilled Red Snapper', 'price': 32}
        ],
        'sides': [
            {'item': 'Tomato Basil Soup', 'price': 5},
            {'item': 'Mashed Potatoes', 'price': 8},
            {'item': 'Grilled Asparagus', 'price': 4},
            {'item': 'Glazed Carrots', 'price': 4},
            {'item': 'Roasted Cauliflower', 'price': 5},
            {'item': 'Side House Salad', 'price': 5},
            {'item': 'Side Caesar Salad', 'price': 5}, 
            {'item': 'Mac & Cheese', 'price': 8}, 
            {'item': 'Steamed Broccoli', 'price': 3}, 
            {'item': 'Seasoned Fries', 'price': 5}, 
            {'item': 'Sweet Potato Fries', 'price': 5}, 
            {'item': 'Onion Rings', 'price': 5}, 
            {'item': 'Pretzel Bites', 'price': 8},
            {'item': 'Steamed Rice', 'price': 5}
        ],
        'beverages': [
            {'item': 'Sweet Tea', 'price': 3}, 
            {'item': 'Iced Tea', 'price': 3},
            {'item': 'Shirley Temple', 'price': 3},
            {'item': 'Arnold Palmer', 'price': 3},
            {'item': 'Pina Colada', 'price': 8},
            {'item': 'Frozen Strawberry Lemonade', 'price': 4},
            {'item': 'Lemonade', 'price': 3}, 
            {'item': 'Sprite', 'price': 3}, 
            {'item': 'Mango Pineapple Smoothie', 'price': 6},
            {'item': 'Strawberry Banana Smoothie', 'price': 6}, 
            {'item': 'Coke', 'price': 3},
            {'item': 'Diet Coke', 'price': 3},
            {'item': 'Coke Zero', 'price': 3}, 
            {'item': 'Milk', 'price': 3},
            {'item': 'San Pellegrino', 'price': 3},
            {'item': 'Bottled Water', 'price': 2},
            {'item': 'Root Beer', 'price': 3}, 
            {'item': 'Gingerale', 'price': 3}, 
            {'item': 'Hot Tea', 'price': 3}, 
            {'item': 'Coffee', 'price': 4}
        ],
        'desserts': [
            {'item': 'Peach Cobbler', 'price': 7}, 
            {'item': 'Strawberry Cheesecake', 'price': 7}, 
            {'item': 'Chocolate Milkshake', 'price': 7}, 
            {'item': 'Vanilla Milkshake', 'price': 7}, 
            {'item': 'Fried Oreos', 'price': 8},
            {'item': 'Funnel Cake Fries', 'price': 8},
            {'item': 'Mango Sorbet', 'price': 5},
            {'item': 'Passion Fruit Sorbet', 'price': 5},
            {'item': 'Melon Sorbet', 'price': 5},
            {'item': 'Tropical Punch Sorbet', 'price': 5},
            {'item': 'Strawberry Milkshake', 'price': 7}, 
            {'item': 'Fudge Brownie', 'price': 5}, 
            {'item': 'Vanilla Sundae', 'price': 9}, 
            {'item': 'Banana Split', 'price': 9}
        ]
    }
}

